route:
  receiver: 'equipe_devops'
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 15m
receivers:
  - name: 'equipe_devops'
    email_configs:
      - to: 'pietro1.com@gmail.com'
        from: 'pietro1.com@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'pietro1.com@gmail.com'
        auth_password_file: '/run/secrets/gmail_app_password'
        require_tls: true
        send_resolved: true
