FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        g++ \
        libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY crow_all.h main.cpp ./

RUN g++ main.cpp -std=c++17 -O2 -pthread -o exportador

EXPOSE 8080

CMD ["./exportador"]
